### ISSUE TITLE
Clicking on directories does not update the URL to include the default file

### ISSUE THREAD

**Issue by abhayghatpande** [justinwalsh/daux.io#381]
I've a directory structure like:

```
docs
.
├── 00_Folder_0
│   ├── 00_File_0.md
│   ├── 01_File_1.md
│   └── 02_File_2.md
├── 01_Folder_1
│   ├── 00_File_0.md
│   ├── 01_File_1.md
│   └── 02_File_2.md
```

In `config.json`, the option `inherit_index` is set to true.

What happens is that if the link for `Folder_0` is clicked for example, the browser displays the contents of `00_File_0.md` as it should -- **EXCEPT** the images are not displayed. The URL in the address bar is `<base_url>/Folder_0`. However, if the contents of the folder are first expanded in the navigation pane and then the link for the file `00_File_0.md` is clicked directly, then everything is displayed correctly. In this case, the URL in the address bar is `<base_url>/Folder_0/File_0`. Note that this problem occurs only for images stored locally and not for those included via remote URLs.

Any ideas how to resolve this?

PS: If `inhert_index` is set to false, clicking on the folder link just expands the tree, and then the link for `00_File_0.md` can be clicked. This solves the issue temporarily as it at least avoids displaying pages without images, though it is not ideal from an UX perspective.

**Comment by abhayghatpande** [comment]
Just realized that this could be related to #374. Sorry for the duplication if that is the case. For now, I'm happy turning off the `inherit_index`.

**Comment by onigoetz** [comment]
Hi,
the management of images is done separately from links so no problem it's not a duplicate ;-)

Can you please check in the inspector to see what url is used to load the images with and without the `inherit_index` option ?

Thanks in advance

**Comment by abhayghatpande** [comment]
The site is accessible at `http://localhost/daux/`

With the `inherit_index` option set to `true`, and the **folder** is clicked, the console shows:

```
http://localhost/daux/image_1.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/daux/image_2.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
```
Additional info:

`baseURI:"http://localhost/daux/folder_1"`
`currentSrc:"http://localhost/daux/image_1.jpg"`

With the `inherit_index` option set to `true`, and the **file** is clicked, there is no error in the console. The image properties show:

`baseURI:"http://localhost/daux/folder_1/file_0"`
`currentSrc:"http://localhost/daux/folder_1/image_1.jpg"`

With the `inherit_index` option set to `false`, clicking on the folder does not display the file at all. So the problem does not arise. When file link is clicked, it is exactly same as the 2nd option above.

Does this help?

**Comment by onigoetz** [comment]
Hello, I'm sorry this took so long, I pushed a fix in the development branch, can you give it a try ?

**Comment by onigoetz** [comment]
Pushed the fix to master but I want to ensure the problem is fixed before closing

**Comment by abhayghatpande** [comment]
I don't think it's working. Checked with both branches. Still get the same errors are before.

**Comment by onigoetz** [comment]
I didn't generate a new `daux.phar` yet, so you will have to do a `composer install` to use the source from `lib`

**Comment by abhayghatpande** [comment]
Thanks. So looks like the `inherit_index` option in `config.json` has no effect any more. 

I can confirm that clicking on the directory now expands the menu rather than displaying the contents of the *first* file. The only exception is when an `index.md` file is present in the directory. This avoids the problem with the images not being displayed.

**Comment by onigoetz** [comment]
Okay, so it seems to work fine.

Yes, I just saw about the option never read, because with the changes I made, the is now in `html` and not in `live` anymore because it also works with generated documentations now.

And the fallback that read the old value from existing configurations was done in the wrong order, this is now fixed.

**Comment by abhayghatpande** [comment]
I'm sorry, I don't really follow because I'm not aware of the inner workings. Are you saying that the `inherit_index` option is now deprecated?

**Comment by onigoetz** [comment]
On the contrary, the `inherit_index` option was in the `live` object before : 
```json
{
  "live": {
    "inherit_index": true
  }
}
```
Because this option was only available in the live mode.
With the new way this works, it also is possible to set this option for the static mode.

Thus I moved this option over to `html`:
```json
{
  "html": {
    "inherit_index": true
  }
}
```

But the code to support the legacy configuration option was in the wrong order and the `$config["live"]["inherit_index"]` was never read, only `$config["html"]["inherit_index"]`.
